idf_component_register(
    SRCS
        "wifi.c"
        "test.c"
        "com.c"
        "router.c"
        "uart_transport.c"
        "aideck_esp_main.c"
        "led.c"
        "spi_transport.c"
        "esp_transport.c"
        "cpx.c"
        "system.c"
        "discovery.c"
        "osc.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp-osc
        spi_flash
        mdns
        nvs_flash
)
